package com.power.oj.bean;

import com.jfinal.plugin.activerecord.Model;

public class Board extends Model<Board>{
	public static final Board dao = new Board();
	public static final String ID = "id";
	public static final String CID = "cid";
	public static final String UID = "uid";
	public static final String ACCEPTS = "accepts";
	public static final String PENALTY = "penalty";
	public static final String A_TIME = "A_time";
	public static final String A_WRONGSUBMITS = "A_WrongSubmits";
	public static final String B_TIME = "B_time";
	public static final String B_WRONGSUBMITS = "B_WrongSubmits";
	public static final String C_TIME = "C_time";
	public static final String C_WRONGSUBMITS = "C_WrongSubmits";
	public static final String D_TIME = "D_time";
	public static final String D_WRONGSUBMITS = "D_WrongSubmits";
	public static final String E_TIME = "E_time";
	public static final String E_WRONGSUBMITS = "E_WrongSubmits";
	public static final String F_TIME = "F_time";
	public static final String F_WRONGSUBMITS = "F_WrongSubmits";
	public static final String G_TIME = "G_time";
	public static final String G_WRONGSUBMITS = "G_WrongSubmits";
	public static final String H_TIME = "H_time";
	public static final String H_WRONGSUBMITS = "H_WrongSubmits";
	public static final String I_TIME = "I_time";
	public static final String I_WRONGSUBMITS = "I_WrongSubmits";
	public static final String J_TIME = "J_time";
	public static final String J_WRONGSUBMITS = "J_WrongSubmits";
	public static final String K_TIME = "K_time";
	public static final String K_WRONGSUBMITS = "K_WrongSubmits";
	public static final String L_TIME = "L_time";
	public static final String L_WRONGSUBMITS = "L_WrongSubmits";
	public static final String M_TIME = "M_time";
	public static final String M_WRONGSUBMITS = "M_WrongSubmits";
	public static final String N_TIME = "N_time";
	public static final String N_WRONGSUBMITS = "N_WrongSubmits";
	public static final String O_TIME = "O_time";
	public static final String O_WRONGSUBMITS = "O_WrongSubmits";
	public static final String P_TIME = "P_time";
	public static final String P_WRONGSUBMITS = "P_WrongSubmits";
	public static final String Q_TIME = "Q_time";
	public static final String Q_WRONGSUBMITS = "Q_WrongSubmits";
	public static final String R_TIME = "R_time";
	public static final String R_WRONGSUBMITS = "R_WrongSubmits";
	public static final String S_TIME = "S_time";
	public static final String S_WRONGSUBMITS = "S_WrongSubmits";
	public static final String T_TIME = "T_time";
	public static final String T_WRONGSUBMITS = "T_WrongSubmits";
	public static final String U_TIME = "U_time";
	public static final String U_WRONGSUBMITS = "U_WrongSubmits";
	public static final String V_TIME = "V_time";
	public static final String V_WRONGSUBMITS = "V_WrongSubmits";
	public static final String W_TIME = "W_time";
	public static final String W_WRONGSUBMITS = "W_WrongSubmits";
	public static final String X_TIME = "X_time";
	public static final String X_WRONGSUBMITS = "X_WrongSubmits";
	public static final String Y_TIME = "Y_time";
	public static final String Y_WRONGSUBMITS = "Y_WrongSubmits";
	public static final String Z_TIME = "Z_time";
	public static final String Z_WRONGSUBMITS = "Z_WrongSubmits";
}
